[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Ensure prisma files are included
[nixpacks]
cmds = ["npm install", "npx prisma generate"]
